server:
  port: 9000

spring:
  application:
    name: authorizationserver

  datasource:
    url: jdbc:mariadb://192.168.1.30:3306/springboottutorial
    username: willy
    password: mO6/DHN[ry
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      
jwt:
  key:
    public: classpath:key.pub
    private: classpath:key.key
    id: spring-boot-tutorial-a3afe780-4dfb-4160-8d8f-b6469b78f073
    